# Generated by Django 5.0.2 on 2024-02-22 12:38

import filestorage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filestorage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to=filestorage.models.user_directory_path),
        ),
    ]
